server:
  port: 8080

mysql:
  datasource:
    ip: 116.63.130.95
    port: 3306
    database: tech_platform
    username: root
    password: ilxw19841201@mysql

console:
   username: admin
   password: 123456789