server:
  port: 8081

mysql:
  datasource:
    ip: 127.0.0.1
    port: 3307
    database: tech_platform
    username: root
    password: test11

console:
  username: admin
  password: 123456789
  healthCheck: false

